### ISSUE TITLE
Do not compile every time in deploy to google app engine

### ISSUE THREAD

**Issue by sinitsyn-alex** [justadudewhohacks/npm-opencv-build#21]
Hey. I use your builds (npm-dlib-build, npm-opencv-build) to recognize faces. When the application is being deployed to the cloud hosting, npm install is executed and each time npm-opencv-build and npm-dlib-build are compiled. Is it possible to avoid this? Let's compile once.

**Comment by justadudewhohacks** [comment]
You will probably have to cache the builds, maybe this can simply be done by caching node_modules. But I think this is nothing, that can be fixed in the install script.
