### ISSUE TITLE
Force installation on Raspberry Pi 3

### ISSUE THREAD

**Issue by bartbutenaers** [justadudewhohacks/npm-opencv-build#6]
Hi Vincent (@justadudewhohacks),

I tried to install opencv4nodejs on my Raspberry Pi 3:
`npm install --save opencv4nodejs`

However it stopped at 60% of the installation (**unsupported platform for fsevents**):

![image](https://user-images.githubusercontent.com/14224149/37178724-a2368544-2323-11e8-860d-c98bbc3b2960.png)

I suppose this is a bit similar to this [issue](https://github.com/angular/angular/issues/13935), because when I **force** it to install:

`npm install --force --save opencv4nodejs`

Then the installation continues without problems:

![image](https://user-images.githubusercontent.com/14224149/37180865-e3bd2796-232a-11e8-8b96-9c3957a4a6d3.png)

Is this perhaps something you could fix somehow (or at least add this workaround to the installation documentation), so other users won't run into the same problems?

I must admit that this is a very convenient way to install OpenCv automatically (as a dependency).  
Very good stuff!!!

Thanks in advance,
Bart Butenaers

**Comment by justadudewhohacks** [comment]
Hi Bart,

Thanks for reporting, seems like some weird issue with npm 3? Anyways, I am not sure if it's nothing that I can fix in this package. But it's good to have this issue, in case some people run into this problem as well. If people start reporting this issue repeatedly I will add a hint in the install section on the main repo.

**Comment by bartbutenaers** [comment]
Hi,

Fair enough.  
It seems the above workaround isn't enough to get it running on a Raspberry.
With the '--force' addition, the installation goes to 100% and then it stops: the Raspberry is completely stuck.

[Some](https://www.pyimagesearch.com/2017/10/09/optimizing-opencv-on-the-raspberry-pi/) extra steps are also needed, to get around that:
- Increase the CONF_SWAPSIZE from 100 to 1024:
    `sudo vim /etc/dphys-swapfile`
- Run the OpenCv installation:
    `npm install --force --save opencv4nodejs`
- Set the CONF_SWAPSIZE back to 100 (to avoid damaging the SD card):
    `sudo vim /etc/dphys-swapfile`

Now it will continue compiling the C++ files. 

I don't know if the all the other steps from the above pyimagesearch link are also needed (like installing the dependency libraries ...), since I already did a manual opencv installation some months ago.  So there is *already* some OpenCv stuff installed on my Raspberry.

I should have a clean installation from scratch to determine what else is needed...  But I assume it is not feasable to put all that stuff in this nodeJs module?

Bart

**Comment by justadudewhohacks** [comment]
I see, unfortunately I am not familar with setting up OpenCV on a Raspberry, all I know is that some people use opencv4nodejs on theirs, not sure if they use their own build or the auto build.

The auto build doesn't set up the other dependencies for you, it just builds opencv for you. So it is assumed that you have build-essentials, cmake, libgtk and image codecs set up on your system, whether Raspberry or not. We can not simply modify the users system by installing packages or modifying config files as this requires priviledged access and stuff.

Also I think the additional configuration required for setting up opencv on a RPI can be done independently from this package. In the end I think, if one wants to build opencv on their RPI, they should know the additional steps as documented in the link you sent.

**Comment by bartbutenaers** [comment]
Hey Vincent,

That is a pitty.  Thought this node would free me from all opencv installation headache. 
Thanks for your time !

Bart

**Comment by Dutu78** [comment]
thx
